project:
  type: website
  output-dir: docs
  resources: 
   - "_lectures"
   - "_homeworks"

website:
  title: "MissingDataMethods2025"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
 