---
title: "Missing Data Methods (Spring 2025; University of Iowa: PSQF 7375)"
---

## Course Objectives

This course section explores missing data methods in applied statistics, data science, and psychometrics; emphasizing techniques such as multiple imputation, Bayesian methods, and maximum likelihood to handle and analyze incomplete data sets effectively.

## Course Readings

The course will follow the chapters of Applied Missing Data Analysis (2nd Edition) by Craig Enders. The University of Iowa Library has electronic access to the book at <https://ebookcentral-proquest-com.proxy.lib.uiowa.edu/lib/uiowa/detail.action?docID=7027149>. Additional readings will be posted our course ICON site.

## Course Details

+--------------------------+---------------------------------------------------------------------------------------+
| Instructor:              | Jonathan Templin                                                                      |
+--------------------------+---------------------------------------------------------------------------------------+
| email:                   | [jonathan-templin\@uiowa.edu](mailto:jonathan-templin@uiowa.edu)                      |
+--------------------------+---------------------------------------------------------------------------------------+
| Course website:          | <https://jonathantemplin.github.io/MissingDataMethods2025/>                           |
+--------------------------+---------------------------------------------------------------------------------------+
| Course repo:             | <https://github.com/jonathantemplin/MissingDataMethods2025>                           |
+--------------------------+---------------------------------------------------------------------------------------+
| Course YouTube Playlist: | <https://www.youtube.com/watch?v=-YUmmA_akLM&list=PLSmMs4UgmSMgYbH3ryj-BTk7F7WWbgWPO> |
+--------------------------+---------------------------------------------------------------------------------------+
| Office:                  | S300A Lindquist Center                                                                |
+--------------------------+---------------------------------------------------------------------------------------+
| Office Phone:            | 319-335-6429                                                                          |
+--------------------------+---------------------------------------------------------------------------------------+
| Classroom:               | S108 LC                                                                               |
+--------------------------+---------------------------------------------------------------------------------------+
| Course Meeting Time:     | W 12:30pm-3:20pm                                                                      |
+--------------------------+---------------------------------------------------------------------------------------+
| Course Office Hours:     | W 10:00am-12:00pm via Zoom at <https://uiowa.zoom.us/my/jonathantemplinuiowa>         |
+--------------------------+---------------------------------------------------------------------------------------+
| Syllabus:                | <https://jonathantemplin.github.io/MissingDataMethods2025/s25mdm_syllabus.html>       |
+--------------------------+---------------------------------------------------------------------------------------+

## Current Assignments

| Assignment                              | Due Date |
|-----------------------------------------|----------|
| Read Enders (2022) Chapter 2            | 4 Feb    |
| Complete Reading Assessment 2 (in ICON) | 4 Feb    |
| Read Enders (2022) Chapter 3            | 11 Feb   |
| Complete Reading Assessment 3 (in ICON) | 11 Feb   |
| Homework #1 (Available in ICON)         | 14 Feb   |

## Lecture and Class Files and Links

```{=html}
<style>
table {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: left;
  padding: 16px;
}
</style>
```

+---------+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| # Date  | # Topic                       | # Materials                                                                                                                                                                  |
+---------+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 22 Jan  | Introduction to class         | -   [Syllabus](https://jonathantemplin.github.io/MissingDataMethods2025/s25mdm_syllabus.html)                                                                                |
|         |                               | -   [Lecture Video](https://www.youtube.com/watch?v=-YUmmA_akLM&list=PLSmMs4UgmSMgYbH3ryj-BTk7F7WWbgWPO)                                                                     |
+---------+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 29 Jan  | Introduction to Missing Data  | -   [Slides (HTML)](https://jonathantemplin.github.io/MissingDataMethods2025/_lectures/01_Introduction_to_Missing_Data/01_Introduction_Missing_Data_S2025.html#/title-slide) |
|         |                               | -   [Slides (PDF)](https://jonathantemplin.github.io/MissingDataMethods2025/_lectures/01_Introduction_to_Missing_Data/01_Introduction_Missing_Data_S2025.pdf)                |
|         |                               | -   [R files](https://github.com/jonathantemplin/MissingDataMethods2025/tree/main/_lectures/01_Introduction_to_Missing_Data)                                                 |
|         |                               | -   [Lecture Video](https://youtu.be/UbO_SZXaTcg)                                                                                                                            |
+---------+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 05 Feb  | Technical Prerequisites       | -   [Slides (PDF)](https://jonathantemplin.github.io/MissingDataMethods2025/_lectures/02_Technical_Prerequisites/02_Technical_Prerequisites_S2025.pdf)                       |
|         |                               | -   [R files](https://github.com/jonathantemplin/MissingDataMethods2025/tree/main/_lectures/02_Technical_Prerequisites)                                                      |
|         |                               | -   [Lecture Video](https://youtu.be/LVLebx5hweI)                                                                                                                            |
+---------+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12 Feb  | Maximum Likelihood Estimation | -   [Slides (PDF)](https://jonathantemplin.github.io/MissingDataMethods2025/_lectures/03_Maximum_Likelihood_Estimation/03_Maximum_Likelihood_Estimation_S2025.pdf)           |
|         |                               | -   [R files](https://github.com/jonathantemplin/MissingDataMethods2025/tree/main/_lectures/03_Maximum_Likelihood_Estimation)                                                |
|         |                               | -   [Lecture Video](https://youtu.be/e4iMA0XB9qw)                                                                                                                            |
+---------+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Remaining Schedule (Tentative)

+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| Week     | Date     | Topic                                                                  | Reading                                        |
+==========+==========+========================================================================+================================================+
| 5        | 19 Feb   | lavaan and Maximum Likelihood Estimation with Missing Data             | Chapter 3                                      |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 6        | 26 Feb   | No Class: Follow Introduction to JAGS activity                         | Chapter 4                                      |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 7        | 5 Mar    | Bayesian Estimation with Missing Data                                  | Chapter 5                                      |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 8        | 12 Mar   | Bayesian Estimation for Categorical Variables                          | Chapter 6                                      |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 9        | 19 Mar   | Spring Break: No Class                                                 | No Readings                                    |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 10       | 26 Mar   | Multiple Imputation                                                    | Chapter 7                                      |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 11       | 2 Apr    | Multilevel Missing Data                                                | Chapter 8                                      |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 12       | 9 Apr    | Missing Not at Random Processes                                        | Chapter 9                                      |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 13       | 16 Apr   | Special Topics and Applications/Guidance for Working with Missing Data | Chapters 10 and 11                             |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 14       | 23 Apr   | Missing Data in Psychometric Models: Latent Variable Scores            | Mislevy et al. (1992)                          |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 15       | 30 Apr   | No Class: AERA/NCME Conference                                         |                                                |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
| 16       | 7 May    | Missing Data in Psychometric Models: Implications for CAT              | Doebler et al. (2013); Jewsbury et al. (2024); |
+----------+----------+------------------------------------------------------------------------+------------------------------------------------+
